# Generated by Django 5.2.7 on 2025-10-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('catalog', '0003_remove_tipocurso_cantidad_participantes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_tesorero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='pel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ruta_foto',
            field=models.CharField(blank=True, db_column='usu_ruta_foto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vigente',
            field=models.BooleanField(db_column='usu_vigente', default=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
