# Generated by Django 5.2.7 on 2025-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prv_id', models.AutoField(primary_key=True, serialize=False)),
                ('prv_descripcion', models.CharField(max_length=100)),
                ('prv_celular1', models.CharField(max_length=15)),
                ('prv_celular2', models.CharField(blank=True, max_length=15, null=True)),
                ('prv_direccion', models.CharField(max_length=100)),
                ('prv_observacion', models.TextField(blank=True, null=True)),
                ('prv_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
    ]
