# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPersona',
            fields=[
                ('arp_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Archivo de Persona',
                'verbose_name_plural': 'Archivos de Persona',
                'db_table': 'archivo_persona',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('arc_id', models.AutoField(primary_key=True, serialize=False)),
                ('arc_fecha_hora', models.DateTimeField()),
                ('arc_descripcion', models.CharField(max_length=100)),
                ('arc_ruta', models.TextField()),
                ('arc_vigente', models.BooleanField()),
                ('tar_id', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.tipoarchivo')),
                ('usu_id_crea', models.ForeignKey(db_column='usu_id_crea', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_creados', to='usuarios.usuario')),
                ('usu_id_modifica', models.ForeignKey(blank=True, db_column='usu_id_modifica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_modificados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivo',
            },
        ),
        migrations.CreateModel(
            name='ArchivoCurso',
            fields=[
                ('aru_id', models.AutoField(primary_key=True, serialize=False)),
                ('arc_id', models.ForeignKey(db_column='arc_id', on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo')),
            ],
            options={
                'verbose_name': 'Archivo de Curso',
                'verbose_name_plural': 'Archivos de Curso',
                'db_table': 'archivo_curso',
            },
        ),
    ]
