# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0001_initial'),
        ('cursos', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocurso',
            name='cus_id',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion'),
        ),
        migrations.AddField(
            model_name='archivopersona',
            name='arc_id',
            field=models.ForeignKey(db_column='arc_id', on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo'),
        ),
        migrations.AddField(
            model_name='archivopersona',
            name='cus_id',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion'),
        ),
        migrations.AddField(
            model_name='archivopersona',
            name='per_id',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AlterUniqueTogether(
            name='archivocurso',
            unique_together={('arc_id', 'cus_id')},
        ),
        migrations.AlterUniqueTogether(
            name='archivopersona',
            unique_together={('arc_id', 'per_id', 'cus_id')},
        ),
    ]
