# Generated by Django 5.2.7 on 2025-10-29 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('celular1', models.CharField(max_length=15)),
                ('celular2', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo', models.IntegerField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
                ('cantidad_participantes', models.IntegerField(blank=True, null=True)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('unilateral', models.BooleanField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAplicacion',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('ingresar', models.BooleanField()),
                ('modificar', models.BooleanField()),
                ('eliminar', models.BooleanField()),
                ('consultar', models.BooleanField()),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.aplicacion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.region'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.zona'),
        ),
    ]
