# Generated by Django 5.2.7 on 2025-10-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='celular2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='cantidad_participantes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
