# Generated by Django 5.2.7 on 2025-10-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_proveedor_celular2_alter_proveedor_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocurso',
            name='cantidad_participantes',
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='cant_participante',
            field=models.IntegerField(blank=True, db_column='tcu_cant_participante', null=True),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='descripcion',
            field=models.CharField(db_column='ali_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='id',
            field=models.DecimalField(db_column='ali_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='tipo',
            field=models.IntegerField(db_column='ali_tipo'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='vigente',
            field=models.BooleanField(db_column='ali_vigente'),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='descripcion',
            field=models.CharField(db_column='apl_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='id',
            field=models.DecimalField(db_column='apl_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='vigente',
            field=models.BooleanField(db_column='apl_vigente'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(db_column='car_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.DecimalField(db_column='car_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='vigente',
            field=models.BooleanField(db_column='car_vigente'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='descripcion',
            field=models.CharField(db_column='com_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id',
            field=models.DecimalField(db_column='com_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.provincia'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='vigente',
            field=models.BooleanField(db_column='com_vigente'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='descripcion',
            field=models.CharField(db_column='dis_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='id',
            field=models.DecimalField(db_column='dis_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='vigente',
            field=models.BooleanField(db_column='dis_vigente'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='zona',
            field=models.ForeignKey(db_column='zon_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.zona'),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='descripcion',
            field=models.CharField(db_column='esc_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='id',
            field=models.DecimalField(db_column='esc_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='vigente',
            field=models.BooleanField(db_column='esc_vigente'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='descripcion',
            field=models.CharField(db_column='gru_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='distrito',
            field=models.ForeignKey(db_column='dis_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.distrito'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.DecimalField(db_column='gru_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='vigente',
            field=models.BooleanField(db_column='gru_vigente'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='descripcion',
            field=models.CharField(db_column='niv_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='id',
            field=models.DecimalField(db_column='niv_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.IntegerField(db_column='niv_orden'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='vigente',
            field=models.BooleanField(db_column='niv_vigente'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(db_column='pel_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.DecimalField(db_column='pel_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vigente',
            field=models.BooleanField(db_column='pel_vigente'),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='aplicacion',
            field=models.ForeignKey(db_column='apl_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.aplicacion'),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='consultar',
            field=models.BooleanField(db_column='pea_consultar'),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='eliminar',
            field=models.BooleanField(db_column='pea_eliminar'),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='id',
            field=models.DecimalField(db_column='pea_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='ingresar',
            field=models.BooleanField(db_column='pea_ingresar'),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='modificar',
            field=models.BooleanField(db_column='pea_modificar'),
        ),
        migrations.AlterField(
            model_name='perfilaplicacion',
            name='perfil',
            field=models.ForeignKey(db_column='pel_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.perfil'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular1',
            field=models.CharField(db_column='prv_celular1', max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular2',
            field=models.CharField(blank=True, db_column='prv_celular2', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(db_column='prv_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(db_column='prv_direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.DecimalField(db_column='prv_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='observacion',
            field=models.TextField(blank=True, db_column='prv_observacion', null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='vigente',
            field=models.BooleanField(db_column='prv_vigente'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='descripcion',
            field=models.CharField(db_column='pro_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.DecimalField(db_column='pro_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(db_column='reg_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.region'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='vigente',
            field=models.BooleanField(db_column='pro_vigente'),
        ),
        migrations.AlterField(
            model_name='rama',
            name='descripcion',
            field=models.CharField(db_column='ram_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='rama',
            name='id',
            field=models.DecimalField(db_column='ram_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rama',
            name='vigente',
            field=models.BooleanField(db_column='ram_vigente'),
        ),
        migrations.AlterField(
            model_name='region',
            name='descripcion',
            field=models.CharField(db_column='reg_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.DecimalField(db_column='reg_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='vigente',
            field=models.BooleanField(db_column='reg_vigente'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(db_column='rol_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.DecimalField(db_column='rol_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.IntegerField(db_column='rol_tipo'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='vigente',
            field=models.BooleanField(db_column='rol_vigente'),
        ),
        migrations.AlterField(
            model_name='tipoarchivo',
            name='descripcion',
            field=models.CharField(db_column='tar_descripcion', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoarchivo',
            name='id',
            field=models.DecimalField(db_column='tar_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoarchivo',
            name='vigente',
            field=models.BooleanField(db_column='tar_vigente'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='descripcion',
            field=models.CharField(db_column='tcu_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='id',
            field=models.DecimalField(db_column='tcu_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='tipo',
            field=models.IntegerField(db_column='tcu_tipo'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='vigente',
            field=models.BooleanField(db_column='tcu_vigente'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='descripcion',
            field=models.CharField(db_column='zon_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id',
            field=models.DecimalField(db_column='zon_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zona',
            name='unilateral',
            field=models.BooleanField(db_column='zon_unilateral'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='vigente',
            field=models.BooleanField(db_column='zon_vigente'),
        ),
        migrations.AlterModelTable(
            name='alimentacion',
            table='alimentacion',
        ),
        migrations.AlterModelTable(
            name='aplicacion',
            table='aplicacion',
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='cargo',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
        migrations.AlterModelTable(
            name='distrito',
            table='distrito',
        ),
        migrations.AlterModelTable(
            name='estadocivil',
            table='estado_civil',
        ),
        migrations.AlterModelTable(
            name='grupo',
            table='grupo',
        ),
        migrations.AlterModelTable(
            name='nivel',
            table='nivel',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
        migrations.AlterModelTable(
            name='perfilaplicacion',
            table='perfil_aplicacion',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='provincia',
        ),
        migrations.AlterModelTable(
            name='rama',
            table='rama',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='tipoarchivo',
            table='tipo_archivo',
        ),
        migrations.AlterModelTable(
            name='tipocurso',
            table='tipo_curso',
        ),
        migrations.AlterModelTable(
            name='zona',
            table='zona',
        ),
    ]
