# Generated by Django 5.2.7 on 2025-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_tipocurso_cantidad_participantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='celular2',
            field=models.CharField(blank=True, db_column='prv_celular2', default='', max_length=15, null=True),
        ),
    ]
