# Generated by Django 5.2.7 on 2025-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_proveedor_celular2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='celular2',
            field=models.CharField(blank=True, db_column='prv_celular2', default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='observacion',
            field=models.TextField(blank=True, db_column='prv_observacion', default=''),
        ),
    ]
