# Generated by Django 5.2.7 on 2025-10-12 16:48

import apps.files.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga de Archivo',
                'verbose_name_plural': 'Descargas de Archivos',
                'db_table': 'file_downloads',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to=apps.files.models.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('tipo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('IMAGEN', 'Imagen'), ('CERTIFICADO', 'Certificado'), ('COMPROBANTE', 'Comprobante de Pago'), ('OTRO', 'Otro')], default='DOCUMENTO', max_length=20)),
                ('estado', models.CharField(choices=[('SUBIDO', 'Subido'), ('VERIFICANDO', 'En Verificación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='SUBIDO', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Si el archivo es público o requiere autenticación')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='courses.course')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'file_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
