from django.contrib import admin
from .models import Region, Provincia, Comuna, Zona, Distrito, Grupo, Rama, Nivel, EstadoCivil, Cargo, TipoArchivo, TipoCurso, Alimentacion, Rol, ConceptoContable, TipoRendicion, TipoDoctoRendicion, TipoMateriales

admin.site.register(Region)
admin.site.register(Provincia)
admin.site.register(Comuna)
admin.site.register(Zona)
admin.site.register(Distrito)
admin.site.register(Grupo)
admin.site.register(Rama)
admin.site.register(Nivel)
admin.site.register(EstadoCivil)
admin.site.register(Cargo)
admin.site.register(TipoArchivo)
admin.site.register(TipoCurso)
admin.site.register(Alimentacion)
admin.site.register(Rol)
admin.site.register(ConceptoContable)
admin.site.register(TipoRendicion)
admin.site.register(TipoDoctoRendicion)
admin.site.register(TipoMateriales)
