# Generated by Django 5.0.7 on 2025-10-29 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('maestros', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='prv_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='prv_descripcion', max_length=100)),
                ('celular1', models.CharField(db_column='prv_celular1', max_length=15)),
                ('celular2', models.CharField(blank=True, db_column='prv_celular2', max_length=15, null=True)),
                ('direccion', models.CharField(db_column='prv_direccion', max_length=100)),
                ('observacion', models.TextField(blank=True, db_column='prv_observacion', null=True)),
                ('vigente', models.BooleanField(db_column='prv_vigente', default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.AutoField(db_column='cpa_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='cpa_fecha_hora', default=django.utils.timezone.now)),
                ('fecha', models.DateField(db_column='cpa_fecha')),
                ('numero', models.IntegerField(db_column='cpa_numero')),
                ('valor', models.DecimalField(db_column='cpa_valor', decimal_places=6, max_digits=21)),
                ('concepto_contable', models.ForeignKey(db_column='coc_id', on_delete=django.db.models.deletion.PROTECT, to='maestros.conceptocontable')),
                ('persona_curso', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.PROTECT, to='cursos.personacurso')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comprobante_pago',
            },
        ),
        migrations.CreateModel(
            name='PagoPersona',
            fields=[
                ('id', models.AutoField(db_column='pap_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='pap_fecha_hora', default=django.utils.timezone.now)),
                ('tipo', models.IntegerField(db_column='pap_tipo')),
                ('valor', models.DecimalField(db_column='pap_valor', decimal_places=6, max_digits=21)),
                ('observacion', models.CharField(blank=True, db_column='pap_observacion', max_length=100, null=True)),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='cursos.curso')),
                ('persona', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='personas.persona')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago_persona',
            },
        ),
        migrations.CreateModel(
            name='PagoComprobante',
            fields=[
                ('id', models.AutoField(db_column='pco_id', primary_key=True, serialize=False)),
                ('comprobante_pago', models.ForeignKey(db_column='cpa_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.comprobantepago')),
                ('pago_persona', models.ForeignKey(db_column='pap_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.pagopersona')),
            ],
            options={
                'db_table': 'pago_comprobante',
            },
        ),
        migrations.CreateModel(
            name='PagoCambioPersona',
            fields=[
                ('id', models.AutoField(db_column='pcp_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='pcp_fecha_hora', default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='personas.persona')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pago_persona', models.ForeignKey(db_column='pap_id', on_delete=django.db.models.deletion.PROTECT, to='pagos.pagopersona')),
            ],
            options={
                'db_table': 'pago_cambio_persona',
            },
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('id', models.AutoField(db_column='ppa_id', primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='ppa_valor', decimal_places=6, max_digits=21)),
                ('observacion', models.TextField(blank=True, db_column='ppa_observacion', null=True)),
                ('vigente', models.BooleanField(db_column='ppa_vigente')),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='cursos.curso')),
                ('pago_persona', models.ForeignKey(blank=True, db_column='pap_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.pagopersona')),
                ('persona', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='personas.persona')),
            ],
            options={
                'db_table': 'prepago',
            },
        ),
    ]
