# Generated by Django 5.0.7 on 2025-10-29 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='cur_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='cur_fecha_hora')),
                ('fecha_solicitud', models.DateTimeField(db_column='cur_fecha_solicitud')),
                ('codigo', models.CharField(db_column='cur_codigo', max_length=10)),
                ('descripcion', models.CharField(blank=True, db_column='cur_descripcion', max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, db_column='cur_observacion', max_length=255, null=True)),
                ('administra', models.IntegerField(db_column='cur_administra')),
                ('cuota_con_almuerzo', models.DecimalField(db_column='cur_cuota_con_almuerzo', decimal_places=6, max_digits=21)),
                ('cuota_sin_almuerzo', models.DecimalField(db_column='cur_cuota_sin_almuerzo', decimal_places=6, max_digits=21)),
                ('modalidad', models.IntegerField(db_column='cur_modalidad')),
                ('lugar', models.CharField(blank=True, db_column='cur_lugar', max_length=100, null=True)),
                ('estado', models.IntegerField(db_column='cur_estado')),
                ('cargo_responsable', models.ForeignKey(db_column='car_id_responsable', on_delete=django.db.models.deletion.PROTECT, to='maestros.cargo')),
                ('lugar_comuna', models.ForeignKey(blank=True, db_column='com_id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.comuna')),
                ('responsable', models.ForeignKey(db_column='per_id_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='cursos_responsable', to='personas.persona')),
                ('tipo_curso', models.ForeignKey(db_column='tcu_id', on_delete=django.db.models.deletion.PROTECT, to='maestros.tipocurso')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='CursoAlimentacion',
            fields=[
                ('id', models.AutoField(db_column='cua_id', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='cua_fecha')),
                ('tiempo', models.IntegerField(db_column='cua_tiempo')),
                ('descripcion', models.CharField(db_column='cua_descripcion', max_length=100)),
                ('cantidad_adicional', models.IntegerField(db_column='cua_cantidad_adicional')),
                ('vigente', models.BooleanField(db_column='cua_vigente')),
                ('alimentacion', models.ForeignKey(db_column='ali_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.alimentacion')),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'db_table': 'curso_alimentacion',
            },
        ),
        migrations.CreateModel(
            name='CursoCoordinador',
            fields=[
                ('id', models.AutoField(db_column='cuc_id', primary_key=True, serialize=False)),
                ('cargo_descripcion', models.CharField(blank=True, db_column='cuc_cargo', max_length=100, null=True)),
                ('cargo', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.cargo')),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('persona', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'db_table': 'curso_coordinador',
            },
        ),
        migrations.CreateModel(
            name='CursoCuota',
            fields=[
                ('id', models.AutoField(db_column='cuu_id', primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(db_column='cuu_tipo')),
                ('fecha', models.DateTimeField(db_column='cuu_fecha')),
                ('valor', models.DecimalField(db_column='cuu_valor', decimal_places=6, max_digits=21)),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'db_table': 'curso_cuota',
            },
        ),
        migrations.CreateModel(
            name='CursoFecha',
            fields=[
                ('id', models.AutoField(db_column='cuf_id', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(db_column='cuf_fecha_inicio')),
                ('fecha_termino', models.DateTimeField(db_column='cuf_fecha_termino')),
                ('tipo', models.IntegerField(db_column='cuf_tipo')),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'db_table': 'curso_fecha',
            },
        ),
        migrations.CreateModel(
            name='CursoSeccion',
            fields=[
                ('id', models.AutoField(db_column='cus_id', primary_key=True, serialize=False)),
                ('seccion', models.IntegerField(db_column='cus_seccion')),
                ('cantidad_participante', models.IntegerField(db_column='cus_cant_participante')),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('rama', models.ForeignKey(blank=True, db_column='ram_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.rama')),
            ],
            options={
                'db_table': 'curso_seccion',
            },
        ),
        migrations.CreateModel(
            name='CursoFormador',
            fields=[
                ('id', models.AutoField(db_column='cuo_id', primary_key=True, serialize=False)),
                ('director', models.BooleanField(db_column='cuo_director')),
                ('curso', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('persona', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.rol')),
                ('curso_seccion', models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion')),
            ],
            options={
                'db_table': 'curso_formador',
            },
        ),
        migrations.CreateModel(
            name='PersonaCurso',
            fields=[
                ('id', models.AutoField(db_column='pec_id', primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, db_column='pec_observacion', null=True)),
                ('registro', models.BooleanField(db_column='pec_registro')),
                ('acreditado', models.BooleanField(db_column='pec_acreditado')),
                ('alimentacion', models.ForeignKey(db_column='ali_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.alimentacion')),
                ('curso_seccion', models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion')),
                ('nivel', models.ForeignKey(blank=True, db_column='niv_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.nivel')),
                ('persona', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, to='maestros.rol')),
            ],
            options={
                'db_table': 'persona_curso',
            },
        ),
        migrations.CreateModel(
            name='PersonaEstadoCurso',
            fields=[
                ('id', models.AutoField(db_column='peu_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='peu_fecha_hora')),
                ('estado', models.IntegerField(db_column='peu_estado')),
                ('vigente', models.BooleanField(db_column='peu_vigente')),
                ('persona_curso', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.personacurso')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona_estado_curso',
            },
        ),
        migrations.CreateModel(
            name='PersonaVehiculo',
            fields=[
                ('id', models.AutoField(db_column='pev_id', primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='pev_marca', max_length=50)),
                ('modelo', models.CharField(db_column='pev_modelo', max_length=50)),
                ('patente', models.CharField(db_column='pev_patente', max_length=10)),
                ('persona_curso', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.personacurso')),
            ],
            options={
                'db_table': 'persona_vehiculo',
            },
        ),
    ]
