# Generated by Django 5.0.7 on 2025-10-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCurso',
            fields=[
                ('id', models.AutoField(db_column='aru_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'archivo_curso',
            },
        ),
        migrations.CreateModel(
            name='ArchivoPersona',
            fields=[
                ('id', models.AutoField(db_column='arp_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'archivo_persona',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(db_column='arc_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='arc_fecha_hora')),
                ('descripcion', models.CharField(db_column='arc_descripcion', max_length=100)),
                ('ruta', models.TextField(db_column='arc_ruta')),
                ('vigente', models.BooleanField(db_column='arc_vigente', default=True)),
                ('tipo_archivo', models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoarchivo')),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
    ]
