# Generated by Django 5.0.7 on 2025-10-29 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0001_initial'),
        ('cursos', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='usuario_crea',
            field=models.ForeignKey(db_column='usu_id_crea', on_delete=django.db.models.deletion.PROTECT, related_name='archivos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, db_column='usu_id_modifica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivocurso',
            name='archivo',
            field=models.ForeignKey(db_column='arc_id', on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo'),
        ),
        migrations.AddField(
            model_name='archivocurso',
            name='curso_seccion',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion'),
        ),
        migrations.AddField(
            model_name='archivopersona',
            name='archivo',
            field=models.ForeignKey(db_column='arc_id', on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo'),
        ),
        migrations.AddField(
            model_name='archivopersona',
            name='curso_seccion',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion'),
        ),
        migrations.AddField(
            model_name='archivopersona',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
    ]
