# Generated by Django 5.2.7 on 2025-11-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0002_password_hashing_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                ("config_key", models.CharField(max_length=100, unique=True)),
                ("config_value", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Email",
                "verbose_name_plural": "Configuraciones de Email",
                "db_table": "email_configuration",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("bounced", "Rebotado"),
                            ("delivered", "Entregado"),
                            ("opened", "Abierto"),
                            ("clicked", "Click en Enlace"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_emails",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Email",
                "verbose_name_plural": "Logs de Email",
                "db_table": "email_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                ("queue_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("context_data", models.JSONField(default=dict)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Baja"),
                            (2, "Normal"),
                            (3, "Alta"),
                            (4, "Urgente"),
                        ],
                        default=2,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cola de Email",
                "verbose_name_plural": "Cola de Emails",
                "db_table": "email_queue",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("file_content", models.BinaryField()),
                ("content_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.emaillog",
                    ),
                ),
                (
                    "email_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.emailqueue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto de Email",
                "verbose_name_plural": "Adjuntos de Email",
                "db_table": "email_attachment",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("template_name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("registration", "Confirmación de Registro"),
                            ("verification", "Verificación de Cuenta"),
                            ("course_enrollment", "Inscripción a Curso"),
                            ("event_qr", "Código QR de Evento"),
                            ("event_reminder", "Recordatorio de Evento"),
                            ("payment_confirmation", "Confirmación de Pago"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Email",
                "verbose_name_plural": "Plantillas de Email",
                "db_table": "email_template",
            },
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="emails.emailtemplate"
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.emailtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["is_processed", "-priority", "created_at"],
                name="email_queue_is_proc_702ed0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["recipient_email", "-created_at"],
                name="email_log_recipie_186420_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["status", "-created_at"], name="email_log_status_c6e787_idx"
            ),
        ),
    ]
