# Generated by Django 5.2.7 on 2025-10-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('courses', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaCurso',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('registro', models.BooleanField()),
                ('acreditado', models.BooleanField()),
                ('alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.alimentacion')),
                ('curso_seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.cursoseccion')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.personanivel')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.rol')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaEstadoCurso',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.IntegerField()),
                ('vigente', models.BooleanField()),
                ('persona_curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preinscriptions.personacurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaVehiculo',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=10)),
                ('persona_curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preinscriptions.personacurso')),
            ],
        ),
    ]
