# Generated by Django 5.2.7 on 2025-10-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacurso',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
