# Generated by Django 5.2.7 on 2025-10-30 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_tipocurso_cantidad_participantes_and_more'),
        ('courses', '0003_alter_curso_administra_alter_curso_cargo_responsable_and_more'),
        ('personas', '0002_remove_persona_apellido_materno_and_more'),
        ('preinscriptions', '0002_alter_personacurso_observacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacurso',
            name='acreditado',
            field=models.BooleanField(db_column='pec_acreditado'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='alimentacion',
            field=models.ForeignKey(db_column='ali_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.alimentacion'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='curso_seccion',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.cursoseccion'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='id',
            field=models.DecimalField(db_column='pec_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='niv_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.nivel'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='observacion',
            field=models.TextField(blank=True, db_column='pec_observacion', null=True),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.RESTRICT, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='registro',
            field=models.BooleanField(db_column='pec_registro'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='rol',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.rol'),
        ),
        migrations.AlterField(
            model_name='personaestadocurso',
            name='estado',
            field=models.IntegerField(db_column='peu_estado'),
        ),
        migrations.AlterField(
            model_name='personaestadocurso',
            name='fecha_hora',
            field=models.DateTimeField(db_column='peu_fecha_hora'),
        ),
        migrations.AlterField(
            model_name='personaestadocurso',
            name='id',
            field=models.DecimalField(db_column='peu_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaestadocurso',
            name='persona_curso',
            field=models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.RESTRICT, to='preinscriptions.personacurso'),
        ),
        migrations.AlterField(
            model_name='personaestadocurso',
            name='usuario',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaestadocurso',
            name='vigente',
            field=models.BooleanField(db_column='peu_vigente'),
        ),
        migrations.AlterField(
            model_name='personavehiculo',
            name='id',
            field=models.DecimalField(db_column='pev_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personavehiculo',
            name='marca',
            field=models.CharField(db_column='pev_marca', max_length=50),
        ),
        migrations.AlterField(
            model_name='personavehiculo',
            name='modelo',
            field=models.CharField(db_column='pev_modelo', max_length=50),
        ),
        migrations.AlterField(
            model_name='personavehiculo',
            name='patente',
            field=models.CharField(db_column='pev_patente', max_length=10),
        ),
        migrations.AlterField(
            model_name='personavehiculo',
            name='persona_curso',
            field=models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.RESTRICT, to='preinscriptions.personacurso'),
        ),
        migrations.AlterModelTable(
            name='personacurso',
            table='persona_curso',
        ),
        migrations.AlterModelTable(
            name='personaestadocurso',
            table='persona_estado_curso',
        ),
        migrations.AlterModelTable(
            name='personavehiculo',
            table='persona_vehiculo',
        ),
    ]
