# Generated by Django 5.2.7 on 2025-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinscriptions', '0003_alter_personacurso_acreditado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacurso',
            name='observacion',
            field=models.TextField(blank=True, db_column='pec_observacion', default='', null=True),
        ),
    ]
