# Generated by Django 5.2.7 on 2025-10-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_proveedor_celular2_alter_proveedor_observacion'),
        ('preinscriptions', '0004_alter_personacurso_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacurso',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='niv_id', default=0, on_delete=django.db.models.deletion.RESTRICT, to='catalog.nivel'),
        ),
        migrations.AlterField(
            model_name='personacurso',
            name='observacion',
            field=models.TextField(blank=True, db_column='pec_observacion', default=''),
        ),
    ]
