# Generated by Django 5.0.7 on 2025-10-20 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['provincia__region__codigo', 'provincia__nombre', 'nombre'], 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['zona__nombre', 'nombre'], 'verbose_name': 'Distrito Scout', 'verbose_name_plural': 'Distritos Scout'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estados Civiles'},
        ),
        migrations.AlterModelOptions(
            name='gruposcout',
            options={'ordering': ['distrito__zona__nombre', 'nombre'], 'verbose_name': 'Grupo Scout', 'verbose_name_plural': 'Grupos Scout'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['rama__codigo', 'orden'], 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['region__codigo', 'nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='rama',
            options={'ordering': ['edad_minima'], 'verbose_name': 'Rama Scout', 'verbose_name_plural': 'Ramas Scout'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['codigo'], 'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='tipoalimentacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Alimentación', 'verbose_name_plural': 'Tipos de Alimentación'},
        ),
        migrations.AlterModelOptions(
            name='tipocurso',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Curso', 'verbose_name_plural': 'Tipos de Curso'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['nombre'], 'verbose_name': 'Zona Scout', 'verbose_name_plural': 'Zonas Scout'},
        ),
        migrations.AlterField(
            model_name='comuna',
            name='codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$', 'Código debe ser numérico')]),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='catalog.provincia'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gruposcout',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gruposcout',
            name='comuna',
            field=models.ForeignKey(blank=True, help_text='Comuna donde se ubica el grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.comuna'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la progresión (0=inicial)'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', 'Código debe ser numérico')]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='catalog.region'),
        ),
        migrations.AlterField(
            model_name='rama',
            name='codigo',
            field=models.CharField(choices=[('CASTORES', 'Castores (5-7 años)'), ('MANADA', 'Manada (7-11 años)'), ('TROPA', 'Tropa (11-15 años)'), ('COMUNIDAD', 'Comunidad (15-18 años)'), ('ROVER', 'Rover (18-21 años)'), ('DIRIGENTES', 'Dirigentes')], max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rama',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Color debe ser hex válido')]),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}$', 'Código debe ser numérico')]),
        ),
        migrations.AlterField(
            model_name='tipoalimentacion',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoalimentacion',
            name='es_restriccion',
            field=models.BooleanField(default=False, help_text='Si es una restricción médica/religiosa vs preferencia'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='codigo',
            field=models.CharField(choices=[('BASICO', 'Formación Básica'), ('INTERMEDIO', 'Formación Intermedia'), ('AVANZADO', 'Formación Avanzada'), ('ESPECIALIDAD', 'Especialidad'), ('PERFECCIONAMIENTO', 'Perfeccionamiento'), ('TALLER', 'Taller'), ('SEMINARIO', 'Seminario')], max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='duracion_default_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Duración típica en horas académicas', null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='region_principal',
            field=models.ForeignKey(blank=True, help_text='Región principal de cobertura de la zona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.region'),
        ),
    ]
