# Generated by Django 5.2.7 on 2025-10-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('run', models.DecimalField(decimal_places=0, max_digits=9)),
                ('dv', models.CharField(max_length=1)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_fono', models.IntegerField()),
                ('fono', models.CharField(max_length=15)),
                ('alergia_enfermedad', models.CharField(blank=True, max_length=255, null=True)),
                ('limitacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fono_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('otros', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_mmaa', models.IntegerField(blank=True, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_nnaj', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_adulto', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('apodo', models.CharField(max_length=50)),
                ('foto', models.TextField(blank=True, null=True)),
                ('vigente', models.BooleanField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.comuna')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.estadocivil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFormador',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('habilitacion_1', models.BooleanField()),
                ('habilitacion_2', models.BooleanField()),
                ('verificacion', models.BooleanField()),
                ('historial', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaIndividual',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('vigente', models.BooleanField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.cargo')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.distrito')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.zona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNivel',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.nivel')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.rama')),
            ],
        ),
    ]
