# Generated by Django 5.2.7 on 2025-10-30 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_tipocurso_cantidad_participantes_and_more'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre_emergencia',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='numero_mmaa',
        ),
        migrations.RemoveField(
            model_name='personaformador',
            name='habilitacion_1',
        ),
        migrations.RemoveField(
            model_name='personaformador',
            name='habilitacion_2',
        ),
        migrations.RemoveField(
            model_name='personaformador',
            name='verificacion',
        ),
        migrations.AddField(
            model_name='persona',
            name='apelmat',
            field=models.CharField(blank=True, db_column='per_apelmat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='apelpat',
            field=models.CharField(blank=True, db_column='per_apelpat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateTimeField(blank=True, db_column='per_fecha_nac', null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nom_emergencia',
            field=models.CharField(blank=True, db_column='per_nom_emergencia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='num_mmaa',
            field=models.IntegerField(blank=True, db_column='per_num_mmaa', null=True),
        ),
        migrations.AddField(
            model_name='personaformador',
            name='hab_1',
            field=models.BooleanField(db_column='pef_hab_1', default=False),
        ),
        migrations.AddField(
            model_name='personaformador',
            name='hab_2',
            field=models.BooleanField(db_column='pef_hab_2', default=False),
        ),
        migrations.AddField(
            model_name='personaformador',
            name='verif',
            field=models.BooleanField(db_column='pef_verif', default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='alergia_enfermedad',
            field=models.CharField(blank=True, db_column='per_alergia_enfermedad', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apodo',
            field=models.CharField(db_column='per_apodo', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comuna',
            field=models.ForeignKey(db_column='com_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.comuna'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(db_column='per_direccion', max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dv',
            field=models.CharField(db_column='per_dv', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(db_column='per_email', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.ForeignKey(db_column='esc_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.estadocivil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_hora',
            field=models.DateTimeField(db_column='per_fecha_hora'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fono',
            field=models.CharField(db_column='per_fono', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fono_emergencia',
            field=models.CharField(blank=True, db_column='per_fono_emergencia', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.TextField(blank=True, db_column='per_foto', null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.DecimalField(db_column='per_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='limitacion',
            field=models.CharField(blank=True, db_column='per_limitacion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(db_column='per_nombres', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otros',
            field=models.CharField(blank=True, db_column='per_otros', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, db_column='per_profesion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='religion',
            field=models.CharField(blank=True, db_column='per_religion', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='run',
            field=models.DecimalField(db_column='per_run', decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tiempo_adulto',
            field=models.CharField(blank=True, db_column='per_tiempo_adulto', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tiempo_nnaj',
            field=models.CharField(blank=True, db_column='per_tiempo_nnaj', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_fono',
            field=models.IntegerField(db_column='per_tipo_fono'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='vigente',
            field=models.BooleanField(db_column='per_vigente'),
        ),
        migrations.AlterField(
            model_name='personaformador',
            name='historial',
            field=models.TextField(blank=True, db_column='pef_historial', null=True),
        ),
        migrations.AlterField(
            model_name='personaformador',
            name='id',
            field=models.DecimalField(db_column='pef_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaformador',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.RESTRICT, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personaindividual',
            name='cargo',
            field=models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.cargo'),
        ),
        migrations.AlterField(
            model_name='personaindividual',
            name='distrito',
            field=models.ForeignKey(blank=True, db_column='dis_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.distrito'),
        ),
        migrations.AlterField(
            model_name='personaindividual',
            name='id',
            field=models.DecimalField(db_column='pei_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaindividual',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.RESTRICT, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personaindividual',
            name='vigente',
            field=models.BooleanField(db_column='pei_vigente'),
        ),
        migrations.AlterField(
            model_name='personaindividual',
            name='zona',
            field=models.ForeignKey(blank=True, db_column='zon_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.zona'),
        ),
        migrations.AlterField(
            model_name='personanivel',
            name='id',
            field=models.DecimalField(db_column='pen_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personanivel',
            name='nivel',
            field=models.ForeignKey(db_column='niv_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.nivel'),
        ),
        migrations.AlterField(
            model_name='personanivel',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.RESTRICT, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personanivel',
            name='rama',
            field=models.ForeignKey(db_column='ram_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.rama'),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='personaformador',
            table='persona_formador',
        ),
        migrations.AlterModelTable(
            name='personaindividual',
            table='persona_individual',
        ),
        migrations.AlterModelTable(
            name='personanivel',
            table='persona_nivel',
        ),
    ]
