# Generated by Django 5.2.7 on 2025-10-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_persona_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='dv',
            new_name='digito_verificador',
        ),
    ]
