# Generated by Django 5.2.7 on 2025-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_rename_dv_persona_digito_verificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='alergia_enfermedad',
            field=models.CharField(blank=True, db_column='per_alergia_enfermedad', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apelmat',
            field=models.CharField(blank=True, db_column='per_apelmat', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apelpat',
            field=models.CharField(blank=True, db_column='per_apelpat', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fono_emergencia',
            field=models.CharField(blank=True, db_column='per_fono_emergencia', default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.TextField(blank=True, db_column='per_foto', default=''),
        ),
        migrations.AlterField(
            model_name='persona',
            name='limitacion',
            field=models.CharField(blank=True, db_column='per_limitacion', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nom_emergencia',
            field=models.CharField(blank=True, db_column='per_nom_emergencia', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otros',
            field=models.CharField(blank=True, db_column='per_otros', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, db_column='per_profesion', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='religion',
            field=models.CharField(blank=True, db_column='per_religion', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tiempo_adulto',
            field=models.CharField(blank=True, db_column='per_tiempo_adulto', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tiempo_nnaj',
            field=models.CharField(blank=True, db_column='per_tiempo_nnaj', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaformador',
            name='historial',
            field=models.TextField(blank=True, db_column='pef_historial', default=''),
        ),
    ]
