# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografia', '0001_initial'),
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAlimentacion',
            fields=[
                ('cua_id', models.AutoField(primary_key=True, serialize=False)),
                ('cua_fecha', models.DateTimeField()),
                ('cua_tiempo', models.IntegerField()),
                ('cua_descripcion', models.CharField(max_length=100)),
                ('cua_cantidad_adicional', models.IntegerField()),
                ('cua_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Alimentación de Curso',
                'verbose_name_plural': 'Alimentaciones de Curso',
                'db_table': 'curso_alimentacion',
            },
        ),
        migrations.CreateModel(
            name='CursoCoordinador',
            fields=[
                ('cuc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuc_cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Coordinador de Curso',
                'verbose_name_plural': 'Coordinadores de Curso',
                'db_table': 'curso_coordinador',
            },
        ),
        migrations.CreateModel(
            name='CursoCuota',
            fields=[
                ('cuu_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuu_tipo', models.IntegerField()),
                ('cuu_fecha', models.DateTimeField()),
                ('cuu_valor', models.DecimalField(decimal_places=6, max_digits=21)),
            ],
            options={
                'verbose_name': 'Cuota de Curso',
                'verbose_name_plural': 'Cuotas de Curso',
                'db_table': 'curso_cuota',
            },
        ),
        migrations.CreateModel(
            name='CursoFecha',
            fields=[
                ('cuf_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuf_fecha_inicio', models.DateTimeField()),
                ('cuf_fecha_termino', models.DateTimeField()),
                ('cuf_tipo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fecha de Curso',
                'verbose_name_plural': 'Fechas de Curso',
                'db_table': 'curso_fecha',
            },
        ),
        migrations.CreateModel(
            name='CursoFormador',
            fields=[
                ('cuo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuo_director', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Formador de Curso',
                'verbose_name_plural': 'Formadores de Curso',
                'db_table': 'curso_formador',
            },
        ),
        migrations.CreateModel(
            name='CursoSeccion',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_seccion', models.IntegerField()),
                ('cus_cant_participante', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sección de Curso',
                'verbose_name_plural': 'Secciones de Curso',
                'db_table': 'curso_seccion',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur_id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cur_fecha_solicitud', models.DateTimeField()),
                ('cur_codigo', models.CharField(max_length=10)),
                ('cur_descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('cur_observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_administra', models.IntegerField()),
                ('cur_cuota_con_almuerzo', models.DecimalField(decimal_places=6, max_digits=21)),
                ('cur_cuota_sin_almuerzo', models.DecimalField(decimal_places=6, max_digits=21)),
                ('cur_modalidad', models.IntegerField()),
                ('cur_tipo_curso', models.IntegerField()),
                ('cur_lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('cur_estado', models.IntegerField()),
                ('car_id_responsable', models.ForeignKey(db_column='car_id_responsable', on_delete=django.db.models.deletion.CASCADE, to='maestros.cargo')),
                ('com_id_lugar', models.ForeignKey(blank=True, db_column='com_id_lugar', null=True, on_delete=django.db.models.deletion.CASCADE, to='geografia.comuna')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
    ]
