# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('maestros', '0001_initial'),
        ('personas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='per_id_responsable',
            field=models.ForeignKey(db_column='per_id_responsable', on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tcu_id',
            field=models.ForeignKey(db_column='tcu_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.tipocurso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='cursoalimentacion',
            name='ali_id',
            field=models.ForeignKey(db_column='ali_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.alimentacion'),
        ),
        migrations.AddField(
            model_name='cursoalimentacion',
            name='cur_id',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursocoordinador',
            name='car_id',
            field=models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.cargo'),
        ),
        migrations.AddField(
            model_name='cursocoordinador',
            name='cur_id',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursocoordinador',
            name='per_id',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='cursocuota',
            name='cur_id',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursofecha',
            name='cur_id',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursoformador',
            name='cur_id',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursoformador',
            name='per_id',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='cursoformador',
            name='rol_id',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.rol'),
        ),
        migrations.AddField(
            model_name='cursoseccion',
            name='cur_id',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursoseccion',
            name='ram_id',
            field=models.ForeignKey(blank=True, db_column='ram_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.rama'),
        ),
        migrations.AddField(
            model_name='cursoformador',
            name='cus_id',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoseccion'),
        ),
        migrations.AlterUniqueTogether(
            name='cursocoordinador',
            unique_together={('cur_id', 'per_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cursoseccion',
            unique_together={('cur_id', 'cus_seccion')},
        ),
        migrations.AlterUniqueTogether(
            name='cursoformador',
            unique_together={('cur_id', 'per_id', 'cus_id')},
        ),
    ]
