# Generated by Django 5.0.7 on 2025-10-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(db_column='ali_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='ali_descripcion', max_length=100)),
                ('tipo', models.IntegerField(db_column='ali_tipo')),
                ('vigente', models.BooleanField(db_column='ali_vigente', default=True)),
            ],
            options={
                'db_table': 'alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(db_column='car_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='car_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='car_vigente', default=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='ConceptoContable',
            fields=[
                ('id', models.AutoField(db_column='coc_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='coc_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='coc_vigente', default=True)),
            ],
            options={
                'db_table': 'concepto_contable',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(db_column='dis_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='dis_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='dis_vigente', default=True)),
            ],
            options={
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(db_column='esc_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='esc_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='esc_vigente', default=True)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(db_column='niv_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='niv_descripcion', max_length=50)),
                ('orden', models.IntegerField(db_column='niv_orden')),
                ('vigente', models.BooleanField(db_column='niv_vigente', default=True)),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(db_column='pro_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='pro_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='pro_vigente', default=True)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.AutoField(db_column='ram_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='ram_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='ram_vigente', default=True)),
            ],
            options={
                'db_table': 'rama',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(db_column='reg_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='reg_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='reg_vigente', default=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='rol_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='rol_descripcion', max_length=50)),
                ('tipo', models.IntegerField(db_column='rol_tipo')),
                ('vigente', models.BooleanField(db_column='rol_vigente', default=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id', models.AutoField(db_column='tar_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='tar_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='tar_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_archivo',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.AutoField(db_column='tcu_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='tcu_descripcion', max_length=100)),
                ('tipo', models.IntegerField(db_column='tcu_tipo')),
                ('cantidad_participante', models.IntegerField(blank=True, db_column='tcu_cant_participante', null=True)),
                ('vigente', models.BooleanField(db_column='tcu_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='TipoDoctoRendicion',
            fields=[
                ('id', models.AutoField(db_column='tdr_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='tdr_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='tdr_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_docto_rendicion',
            },
        ),
        migrations.CreateModel(
            name='TipoMateriales',
            fields=[
                ('id', models.AutoField(db_column='tma_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='tma_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='tma_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_materiales',
            },
        ),
        migrations.CreateModel(
            name='TipoRendicion',
            fields=[
                ('id', models.AutoField(db_column='tre_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='tre_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='tre_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_rendicion',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(db_column='zon_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='zon_descripcion', max_length=100)),
                ('unilateral', models.BooleanField(db_column='zon_unilateral')),
                ('vigente', models.BooleanField(db_column='zon_vigente', default=True)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(db_column='gru_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='gru_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='gru_vigente', default=True)),
                ('distrito', models.ForeignKey(db_column='dis_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='maestros.distrito')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(db_column='com_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='com_descripcion', max_length=100)),
                ('vigente', models.BooleanField(db_column='com_vigente', default=True)),
                ('provincia', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='maestros.provincia')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(db_column='reg_id', on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='maestros.region'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='zona',
            field=models.ForeignKey(db_column='zon_id', on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='maestros.zona'),
        ),
    ]
