# Generated by Django 5.2.7 on 2025-10-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('fecha_solicitud', models.DateTimeField()),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('administra', models.IntegerField()),
                ('cuota_con_almuerzo', models.DecimalField(decimal_places=6, max_digits=21)),
                ('cuota_sin_almuerzo', models.DecimalField(decimal_places=6, max_digits=21)),
                ('modalidad', models.IntegerField()),
                ('tipo_curso_enum', models.IntegerField()),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField()),
                ('cargo_responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.cargo')),
                ('comuna_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.comuna')),
                ('persona_responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('tipo_curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.tipocurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CursoAlimentacion',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('tiempo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_adicional', models.IntegerField()),
                ('vigente', models.BooleanField()),
                ('alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.alimentacion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCoordinador',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('cargo_coordinador', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.cargo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCuota',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoFecha',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('tipo', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoSeccion',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('seccion', models.IntegerField()),
                ('cantidad_participantes', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
                ('rama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.rama')),
            ],
        ),
        migrations.CreateModel(
            name='CursoFormador',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('director', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.rol')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.cursoseccion')),
            ],
        ),
    ]
