# Generated by Django 5.2.7 on 2025-10-30 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_tipocurso_cantidad_participantes_and_more'),
        ('courses', '0002_alter_curso_descripcion_alter_curso_lugar_and_more'),
        ('personas', '0002_remove_persona_apellido_materno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='administra',
            field=models.IntegerField(db_column='cur_administra'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cargo_responsable',
            field=models.ForeignKey(db_column='car_id_responsable', on_delete=django.db.models.deletion.RESTRICT, to='catalog.cargo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(db_column='cur_codigo', max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='comuna_lugar',
            field=models.ForeignKey(blank=True, db_column='com_id_lugar', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.comuna'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cuota_con_almuerzo',
            field=models.DecimalField(db_column='cur_cuota_con_almuerzo', decimal_places=6, max_digits=21),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cuota_sin_almuerzo',
            field=models.DecimalField(db_column='cur_cuota_sin_almuerzo', decimal_places=6, max_digits=21),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(blank=True, db_column='cur_descripcion', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.IntegerField(db_column='cur_estado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_hora',
            field=models.DateTimeField(db_column='cur_fecha_hora'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_solicitud',
            field=models.DateTimeField(db_column='cur_fecha_solicitud'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.DecimalField(db_column='cur_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='lugar',
            field=models.CharField(blank=True, db_column='cur_lugar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.IntegerField(db_column='cur_modalidad'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='observacion',
            field=models.CharField(blank=True, db_column='cur_observacion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='persona_responsable',
            field=models.ForeignKey(db_column='per_id_responsable', on_delete=django.db.models.deletion.RESTRICT, related_name='cursos_responsable', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_curso',
            field=models.ForeignKey(db_column='tcu_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.tipocurso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_curso_enum',
            field=models.IntegerField(db_column='cur_tipo_curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='alimentacion',
            field=models.ForeignKey(db_column='ali_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.alimentacion'),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='cantidad_adicional',
            field=models.IntegerField(db_column='cua_cantidad_adicional'),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='curso',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='descripcion',
            field=models.CharField(db_column='cua_descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='fecha',
            field=models.DateTimeField(db_column='cua_fecha'),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='id',
            field=models.DecimalField(db_column='cua_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='tiempo',
            field=models.IntegerField(db_column='cua_tiempo'),
        ),
        migrations.AlterField(
            model_name='cursoalimentacion',
            name='vigente',
            field=models.BooleanField(db_column='cua_vigente'),
        ),
        migrations.AlterField(
            model_name='cursocoordinador',
            name='cargo',
            field=models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.cargo'),
        ),
        migrations.AlterField(
            model_name='cursocoordinador',
            name='cargo_coordinador',
            field=models.CharField(blank=True, db_column='cuc_cargo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cursocoordinador',
            name='curso',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='cursocoordinador',
            name='id',
            field=models.DecimalField(db_column='cuc_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursocoordinador',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.RESTRICT, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='cursocuota',
            name='curso',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='cursocuota',
            name='fecha',
            field=models.DateTimeField(db_column='cuu_fecha'),
        ),
        migrations.AlterField(
            model_name='cursocuota',
            name='id',
            field=models.DecimalField(db_column='cuu_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursocuota',
            name='tipo',
            field=models.IntegerField(db_column='cuu_tipo'),
        ),
        migrations.AlterField(
            model_name='cursocuota',
            name='valor',
            field=models.DecimalField(db_column='cuu_valor', decimal_places=6, max_digits=21),
        ),
        migrations.AlterField(
            model_name='cursofecha',
            name='curso',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='cursofecha',
            name='fecha_inicio',
            field=models.DateTimeField(db_column='cuf_fecha_inicio'),
        ),
        migrations.AlterField(
            model_name='cursofecha',
            name='fecha_termino',
            field=models.DateTimeField(db_column='cuf_fecha_termino'),
        ),
        migrations.AlterField(
            model_name='cursofecha',
            name='id',
            field=models.DecimalField(db_column='cuf_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursofecha',
            name='tipo',
            field=models.IntegerField(db_column='cuf_tipo'),
        ),
        migrations.AlterField(
            model_name='cursoformador',
            name='curso',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='cursoformador',
            name='director',
            field=models.BooleanField(db_column='cuo_director'),
        ),
        migrations.AlterField(
            model_name='cursoformador',
            name='id',
            field=models.DecimalField(db_column='cuo_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursoformador',
            name='persona',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.RESTRICT, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='cursoformador',
            name='rol',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.rol'),
        ),
        migrations.AlterField(
            model_name='cursoformador',
            name='seccion',
            field=models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.RESTRICT, to='courses.cursoseccion'),
        ),
        migrations.AlterField(
            model_name='cursoseccion',
            name='cantidad_participantes',
            field=models.IntegerField(db_column='cus_cant_participante'),
        ),
        migrations.AlterField(
            model_name='cursoseccion',
            name='curso',
            field=models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.RESTRICT, related_name='secciones', to='courses.curso'),
        ),
        migrations.AlterField(
            model_name='cursoseccion',
            name='id',
            field=models.DecimalField(db_column='cus_id', decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursoseccion',
            name='rama',
            field=models.ForeignKey(blank=True, db_column='ram_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.rama'),
        ),
        migrations.AlterField(
            model_name='cursoseccion',
            name='seccion',
            field=models.IntegerField(db_column='cus_seccion'),
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='cursoalimentacion',
            table='curso_alimentacion',
        ),
        migrations.AlterModelTable(
            name='cursocoordinador',
            table='curso_coordinador',
        ),
        migrations.AlterModelTable(
            name='cursocuota',
            table='curso_cuota',
        ),
        migrations.AlterModelTable(
            name='cursofecha',
            table='curso_fecha',
        ),
        migrations.AlterModelTable(
            name='cursoformador',
            table='curso_formador',
        ),
        migrations.AlterModelTable(
            name='cursoseccion',
            table='curso_seccion',
        ),
    ]
