# Generated by Django 5.2.7 on 2025-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_curso_administra_alter_curso_cargo_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoseccion',
            name='cupos',
            field=models.IntegerField(db_column='cus_cupos', default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(blank=True, db_column='cur_descripcion', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='lugar',
            field=models.CharField(blank=True, db_column='cur_lugar', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='observacion',
            field=models.CharField(blank=True, db_column='cur_observacion', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cursocoordinador',
            name='cargo_coordinador',
            field=models.CharField(blank=True, db_column='cuc_cargo', default='', max_length=100),
        ),
    ]
