# Generated by Django 5.2.7 on 2025-10-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('personas', '0001_initial'),
        ('preinscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoContable',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('fecha', models.DateField()),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('persona_curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preinscriptions.personacurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('concepto_contable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.conceptocontable')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPersona',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoComprobante',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('comprobante_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.comprobantepago')),
                ('pago_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.pagopersona')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCambioPersona',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('pago_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.pagopersona')),
            ],
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('vigente', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.curso')),
                ('pago_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='payments.pagopersona')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
            ],
        ),
    ]
