# Generated by Django 5.2.7 on 2025-10-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopersona',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='pago_persona',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.RESTRICT, to='payments.pagopersona'),
        ),
    ]
