# Generated by Django 5.2.7 on 2025-10-12 16:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Categoría activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Curso',
                'verbose_name_plural': 'Categorías de Cursos',
                'db_table': 'courses_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del curso')),
                ('description', models.TextField(verbose_name='Descripción del curso')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código único del curso')),
                ('rama', models.CharField(choices=[('MANADA', 'Manada (7-11 años)'), ('TROPA', 'Tropa (11-15 años)'), ('COMUNIDAD', 'Comunidad (15-18 años)'), ('ROVER', 'Rover (18-21 años)'), ('DIRIGENTES', 'Dirigentes'), ('GENERAL', 'General (todas las ramas)')], default='GENERAL', max_length=20, verbose_name='Rama Scout objetivo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=10, verbose_name='Estado del curso')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio del curso')),
                ('max_participants', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de participantes')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Categoría del curso')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COORDINADOR', 'Coordinador de Curso'), ('FORMADOR', 'Formador/Instructor'), ('ASISTENTE', 'Asistente de Coordinación'), ('OBSERVADOR', 'Observador/Evaluador')], max_length=20, verbose_name='Rol en el equipo')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='courses.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Miembro del equipo')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo de Curso',
                'verbose_name_plural': 'Equipos de Cursos',
                'db_table': 'course_teams',
                'unique_together': {('course', 'user', 'role')},
            },
        ),
    ]
