# Generated by Django 5.2.7 on 2025-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('ali_id', models.AutoField(primary_key=True, serialize=False)),
                ('ali_descripcion', models.CharField(max_length=100)),
                ('ali_tipo', models.IntegerField()),
                ('ali_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Alimentación',
                'verbose_name_plural': 'Alimentaciones',
                'db_table': 'alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('apl_id', models.AutoField(primary_key=True, serialize=False)),
                ('apl_descripcion', models.CharField(max_length=50)),
                ('apl_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'db_table': 'aplicacion',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_descripcion', models.CharField(max_length=100)),
                ('car_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='ConceptoContable',
            fields=[
                ('coc_id', models.AutoField(primary_key=True, serialize=False)),
                ('coc_descripcion', models.CharField(max_length=50)),
                ('coc_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Concepto Contable',
                'verbose_name_plural': 'Conceptos Contables',
                'db_table': 'concepto_contable',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('esc_id', models.AutoField(primary_key=True, serialize=False)),
                ('esc_descripcion', models.CharField(max_length=50)),
                ('esc_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('niv_id', models.AutoField(primary_key=True, serialize=False)),
                ('niv_descripcion', models.CharField(max_length=50)),
                ('niv_orden', models.IntegerField()),
                ('niv_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('pel_id', models.AutoField(primary_key=True, serialize=False)),
                ('pel_descripcion', models.CharField(max_length=50)),
                ('pel_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('ram_id', models.AutoField(primary_key=True, serialize=False)),
                ('ram_descripcion', models.CharField(max_length=50)),
                ('ram_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Rama',
                'verbose_name_plural': 'Ramas',
                'db_table': 'rama',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_descripcion', models.CharField(max_length=50)),
                ('rol_tipo', models.IntegerField()),
                ('rol_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('tar_id', models.AutoField(primary_key=True, serialize=False)),
                ('tar_descripcion', models.CharField(max_length=50)),
                ('tar_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tipo de Archivo',
                'verbose_name_plural': 'Tipos de Archivo',
                'db_table': 'tipo_archivo',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('tcu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tcu_descripcion', models.CharField(max_length=100)),
                ('tcu_tipo', models.IntegerField()),
                ('tcu_cant_participante', models.IntegerField(blank=True, null=True)),
                ('tcu_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Curso',
                'db_table': 'tipo_curso',
            },
        ),
    ]
