# Generated by Django 5.2.7 on 2025-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="comprobante",
            field=models.FileField(
                blank=True,
                help_text="Comprobante de pago adjunto",
                null=True,
                upload_to="comprobantes_pago/",
            ),
        ),
    ]
