# Generated by Django 5.2.7 on 2025-10-14 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_cuota_unique_together_remove_cuota_pago_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoContable",
            fields=[
                ("COC_ID", models.AutoField(primary_key=True, serialize=False)),
                ("COC_DESCRIPCION", models.CharField(max_length=50)),
                ("COC_VIGENTE", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Concepto Contable",
                "verbose_name_plural": "Conceptos Contables",
                "db_table": "CONCEPTO_CONTABLE",
            },
        ),
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                ("CPA_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PEC_ID", models.IntegerField()),
                ("CPA_FECHA_HORA", models.DateTimeField()),
                ("CPA_FECHA", models.DateField()),
                ("CPA_NUMERO", models.IntegerField()),
                ("CPA_VALOR", models.DecimalField(decimal_places=6, max_digits=21)),
                (
                    "USU_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "COC_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes_concepto",
                        to="payments.conceptocontable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante de Pago",
                "verbose_name_plural": "Comprobantes de Pagos",
                "db_table": "COMPROBANTE_PAGO",
            },
        ),
        migrations.CreateModel(
            name="PagoPersona",
            fields=[
                ("PAP_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PER_ID", models.IntegerField()),
                ("CUR_ID", models.IntegerField()),
                ("PAP_FECHA_HORA", models.DateTimeField()),
                (
                    "PAP_TIPO",
                    models.IntegerField(
                        choices=[(1, "Ingreso"), (2, "Egreso")], default=1
                    ),
                ),
                ("PAP_VALOR", models.DecimalField(decimal_places=6, max_digits=21)),
                (
                    "PAP_OBSERVACION",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "USU_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Persona",
                "verbose_name_plural": "Pagos de Personas",
                "db_table": "PAGO_PERSONA",
            },
        ),
        migrations.CreateModel(
            name="PagoComprobante",
            fields=[
                ("PCO_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CPA_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes_pago",
                        to="payments.comprobantepago",
                    ),
                ),
                (
                    "PAP_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_comprobante",
                        to="payments.pagopersona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Comprobante",
                "verbose_name_plural": "Pagos Comprobantes",
                "db_table": "PAGO_COMPROBANTE",
            },
        ),
        migrations.CreateModel(
            name="PagoCambioPersona",
            fields=[
                ("PCP_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PER_ID", models.IntegerField()),
                ("PCP_FECHA_HORA", models.DateTimeField()),
                (
                    "USU_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios_pago_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "PAP_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios_pago",
                        to="payments.pagopersona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Cambio Persona",
                "verbose_name_plural": "Pagos Cambios Personas",
                "db_table": "PAGO_CAMBIO_PERSONA",
            },
        ),
        migrations.CreateModel(
            name="Prepago",
            fields=[
                ("PPA_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PER_ID", models.IntegerField()),
                ("CUR_ID", models.IntegerField()),
                ("PPA_VALOR", models.DecimalField(decimal_places=6, max_digits=21)),
                ("PPA_OBSERVACION", models.TextField(blank=True, null=True)),
                ("PPA_VIGENTE", models.BooleanField(default=True)),
                (
                    "PAP_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepago_asociado",
                        to="payments.pagopersona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prepago",
                "verbose_name_plural": "Prepagos",
                "db_table": "PREPAGO",
            },
        ),
    ]
