# Generated by Django 5.0.7 on 2025-10-20 05:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_conceptocontable_comprobantepago_pagopersona_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='preinscripcion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='registrado_por',
        ),
        migrations.AlterModelOptions(
            name='comprobantepago',
            options={'ordering': ['-CPA_FECHA', '-CPA_NUMERO'], 'verbose_name': 'Comprobante de Pago', 'verbose_name_plural': 'Comprobantes de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='conceptocontable',
            options={'ordering': ['COC_DESCRIPCION'], 'verbose_name': 'Concepto Contable', 'verbose_name_plural': 'Conceptos Contables'},
        ),
        migrations.AlterModelOptions(
            name='pagocambiopersona',
            options={'ordering': ['-PCP_FECHA_HORA'], 'verbose_name': 'Historial de Cambio de Pago', 'verbose_name_plural': 'Historiales de Cambios de Pago'},
        ),
        migrations.AlterModelOptions(
            name='pagocomprobante',
            options={'verbose_name': 'Relación Pago-Comprobante', 'verbose_name_plural': 'Relaciones Pago-Comprobante'},
        ),
        migrations.AlterModelOptions(
            name='pagopersona',
            options={'ordering': ['-PAP_FECHA_HORA'], 'verbose_name': 'Pago de Persona', 'verbose_name_plural': 'Pagos de Personas'},
        ),
        migrations.AlterModelOptions(
            name='prepago',
            options={'ordering': ['-PPA_ID'], 'verbose_name': 'Prepago (Saldo a Favor)', 'verbose_name_plural': 'Prepagos (Saldos a Favor)'},
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='COC_ID',
            field=models.ForeignKey(help_text='Concepto contable principal del comprobante.', on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_concepto', to='payments.conceptocontable'),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_FECHA',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha del comprobante (sin hora) para reportes.'),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_FECHA_HORA',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de emisión del comprobante.'),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_ID',
            field=models.AutoField(help_text='Identificador único del comprobante.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_NUMERO',
            field=models.IntegerField(help_text='Número correlativo y único del comprobante.', unique=True),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_VALOR',
            field=models.DecimalField(decimal_places=2, help_text='Valor total del comprobante, puede ser la suma de varios pagos.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='PEC_ID',
            field=models.IntegerField(help_text='ID de la Persona-Curso a la que se emite el comprobante. FK a PersonaCurso.'),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='USU_ID',
            field=models.ForeignKey(help_text='Usuario que emitió el comprobante.', on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conceptocontable',
            name='COC_DESCRIPCION',
            field=models.CharField(help_text="Nombre descriptivo del concepto (ej. 'Inscripción Anual').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='conceptocontable',
            name='COC_ID',
            field=models.AutoField(help_text='Identificador único del concepto contable.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conceptocontable',
            name='COC_VIGENTE',
            field=models.BooleanField(default=True, help_text='Indica si el concepto está activo y puede ser utilizado en nuevas transacciones.'),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PAP_ID',
            field=models.ForeignKey(help_text='Pago original que se está transfiriendo.', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_pago', to='payments.pagopersona'),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PCP_FECHA_HORA',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó el cambio.'),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PCP_ID',
            field=models.AutoField(help_text='Identificador único del registro de cambio.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PER_ID',
            field=models.IntegerField(help_text='ID de la nueva persona a la que se le asigna el pago. FK al modelo de Personas.'),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='USU_ID',
            field=models.ForeignKey(help_text='Usuario que autorizó y registró el cambio.', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_pago_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagocomprobante',
            name='CPA_ID',
            field=models.ForeignKey(help_text='Comprobante que agrupa el pago.', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_pago', to='payments.comprobantepago'),
        ),
        migrations.AlterField(
            model_name='pagocomprobante',
            name='PAP_ID',
            field=models.ForeignKey(help_text='Pago que forma parte del comprobante.', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_comprobante', to='payments.pagopersona'),
        ),
        migrations.AlterField(
            model_name='pagocomprobante',
            name='PCO_ID',
            field=models.AutoField(help_text='Identificador único de la relación.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='CUR_ID',
            field=models.IntegerField(help_text='ID del curso asociado al pago. Futura FK al modelo de Cursos.'),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_FECHA_HORA',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora exactas en que se registra el pago.'),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_ID',
            field=models.AutoField(help_text='Identificador único del pago.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_OBSERVACION',
            field=models.CharField(blank=True, help_text="Notas adicionales sobre el pago (ej. 'Abono 50%').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_TIPO',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], default=1, help_text='Clasifica el movimiento: 1 para Ingreso (ej. abono) y 2 para Egreso (ej. devolución).'),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_VALOR',
            field=models.DecimalField(decimal_places=2, help_text='Monto del pago. Debe ser un valor positivo.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PER_ID',
            field=models.IntegerField(help_text='ID de la persona que realiza o recibe el pago. FK al modelo de Personas.'),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='USU_ID',
            field=models.ForeignKey(help_text='Usuario que registra la transacción.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='CUR_ID',
            field=models.IntegerField(help_text='ID del curso donde se puede usar este saldo. FK al modelo de Cursos.'),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PAP_ID',
            field=models.ForeignKey(blank=True, help_text='Pago original que generó este saldo a favor (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepago_asociado', to='payments.pagopersona'),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PER_ID',
            field=models.IntegerField(help_text='ID de la persona a la que pertenece el saldo. FK al modelo de Personas.'),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_ID',
            field=models.AutoField(help_text='Identificador único del prepago.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_OBSERVACION',
            field=models.TextField(blank=True, help_text='Notas sobre el origen o condición del prepago.', null=True),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_VALOR',
            field=models.DecimalField(decimal_places=2, help_text='Monto del saldo a favor.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_VIGENTE',
            field=models.BooleanField(default=True, help_text='Indica si el saldo a favor todavía está disponible para ser usado.'),
        ),
        migrations.AlterUniqueTogether(
            name='pagocomprobante',
            unique_together={('PAP_ID', 'CPA_ID')},
        ),
        migrations.AlterModelTable(
            name='comprobantepago',
            table='comprobante_pago',
        ),
        migrations.AlterModelTable(
            name='conceptocontable',
            table='concepto_contable',
        ),
        migrations.AlterModelTable(
            name='pagocambiopersona',
            table='pago_cambio_persona',
        ),
        migrations.AlterModelTable(
            name='pagocomprobante',
            table='pago_comprobante',
        ),
        migrations.AlterModelTable(
            name='pagopersona',
            table='pago_persona',
        ),
        migrations.AlterModelTable(
            name='prepago',
            table='prepago',
        ),
        migrations.DeleteModel(
            name='ComprobanteDescarga',
        ),
        migrations.DeleteModel(
            name='Cuota',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
