# Generated by Django 5.0.7 on 2025-10-20 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('payments', '9999_remove_legacy_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Legacy Pago (compat)', 'verbose_name_plural': 'Legacy Pagos (compat)'},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='pagopersona',
            name='CUR_FK',
            field=models.ForeignKey(blank=True, db_column='CUR_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_persona_cur_fk', to='courses.course'),
        ),
        migrations.AddField(
            model_name='pagopersona',
            name='PER_FK',
            field=models.ForeignKey(blank=True, db_column='PER_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_persona_per_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='COC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_concepto', to='payments.conceptocontable'),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_FECHA',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_FECHA_HORA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_NUMERO',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='CPA_VALOR',
            field=models.DecimalField(decimal_places=6, max_digits=21),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='PEC_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conceptocontable',
            name='COC_DESCRIPCION',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='conceptocontable',
            name='COC_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conceptocontable',
            name='COC_VIGENTE',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PAP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_pago', to='payments.pagopersona'),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PCP_FECHA_HORA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PCP_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='PER_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pagocambiopersona',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_pago_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagocomprobante',
            name='CPA_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_pago', to='payments.comprobantepago'),
        ),
        migrations.AlterField(
            model_name='pagocomprobante',
            name='PAP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_comprobante', to='payments.pagopersona'),
        ),
        migrations.AlterField(
            model_name='pagocomprobante',
            name='PCO_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_FECHA_HORA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_OBSERVACION',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_TIPO',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], default=1),
        ),
        migrations.AlterField(
            model_name='pagopersona',
            name='PAP_VALOR',
            field=models.DecimalField(decimal_places=6, help_text='Monto del pago', max_digits=21),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='CUR_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PAP_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepago_asociado', to='payments.pagopersona'),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PER_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_OBSERVACION',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_VALOR',
            field=models.DecimalField(decimal_places=6, max_digits=21),
        ),
        migrations.AlterField(
            model_name='prepago',
            name='PPA_VIGENTE',
            field=models.BooleanField(default=True),
        ),
    ]
