# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_username', models.CharField(max_length=100, unique=True)),
                ('usu_password', models.CharField(max_length=50)),
                ('usu_email', models.EmailField(max_length=100)),
                ('usu_ruta_foto', models.CharField(max_length=255)),
                ('usu_vigente', models.BooleanField()),
                ('pel_id', models.ForeignKey(db_column='pel_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.perfil')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilAplicacion',
            fields=[
                ('pea_id', models.AutoField(primary_key=True, serialize=False)),
                ('pea_ingresar', models.BooleanField()),
                ('pea_modificar', models.BooleanField()),
                ('pea_eliminar', models.BooleanField()),
                ('pea_consultar', models.BooleanField()),
                ('apl_id', models.ForeignKey(db_column='apl_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.aplicacion')),
                ('pel_id', models.ForeignKey(db_column='pel_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.perfil')),
            ],
            options={
                'verbose_name': 'Perfil Aplicación',
                'verbose_name_plural': 'Perfiles Aplicaciones',
                'db_table': 'perfil_aplicacion',
                'unique_together': {('pel_id', 'apl_id')},
            },
        ),
    ]
