# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_descripcion', models.CharField(max_length=100)),
                ('dis_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_descripcion', models.CharField(max_length=100)),
                ('pro_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_descripcion', models.CharField(max_length=100)),
                ('reg_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zon_id', models.AutoField(primary_key=True, serialize=False)),
                ('zon_descripcion', models.CharField(max_length=100)),
                ('zon_unilateral', models.BooleanField()),
                ('zon_vigente', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('gru_id', models.AutoField(primary_key=True, serialize=False)),
                ('gru_descripcion', models.CharField(max_length=100)),
                ('gru_vigente', models.BooleanField()),
                ('dis_id', models.ForeignKey(db_column='dis_id', on_delete=django.db.models.deletion.CASCADE, to='geografia.distrito')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_descripcion', models.CharField(max_length=100)),
                ('com_vigente', models.BooleanField()),
                ('pro_id', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='geografia.provincia')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='reg_id',
            field=models.ForeignKey(db_column='reg_id', on_delete=django.db.models.deletion.CASCADE, to='geografia.region'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='zon_id',
            field=models.ForeignKey(db_column='zon_id', on_delete=django.db.models.deletion.CASCADE, to='geografia.zona'),
        ),
    ]
