# Generated by Django 5.2.7 on 2025-10-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('courses', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('arc_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('arc_fecha_hora', models.DateTimeField()),
                ('arc_descripcion', models.CharField(max_length=100)),
                ('arc_ruta', models.TextField()),
                ('arc_vigente', models.BooleanField()),
                ('tar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.tipoarchivo')),
                ('usu_id_crea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='archivos_creados', to=settings.AUTH_USER_MODEL)),
                ('usu_id_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='archivos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCurso',
            fields=[
                ('aru_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='files.archivo')),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.cursoseccion')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoPersona',
            fields=[
                ('arp_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='files.archivo')),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.cursoseccion')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
            ],
        ),
    ]
