# Generated by Django 5.2.7 on 2025-10-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='arc_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='arc_fecha_hora',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='arc_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='arc_ruta',
            new_name='ruta',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='tar',
            new_name='tipo_archivo',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='usu_id_crea',
            new_name='usuario_crea',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='usu_id_modifica',
            new_name='usuario_modifica',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='arc_vigente',
            new_name='vigente',
        ),
        migrations.RenameField(
            model_name='archivocurso',
            old_name='arc',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='archivocurso',
            old_name='cus',
            new_name='curso_seccion',
        ),
        migrations.RenameField(
            model_name='archivocurso',
            old_name='aru_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='archivopersona',
            old_name='arc',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='archivopersona',
            old_name='cus',
            new_name='curso_seccion',
        ),
        migrations.RenameField(
            model_name='archivopersona',
            old_name='arp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='archivopersona',
            old_name='per',
            new_name='persona',
        ),
    ]
