# Generated by Django 5.2.7 on 2025-11-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_initial'),
        ('maestros', '0001_initial'),
        ('personas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('cpa_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpa_fecha_hora', models.DateTimeField()),
                ('cpa_fecha', models.DateField()),
                ('cpa_numero', models.IntegerField()),
                ('cpa_valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('coc_id', models.ForeignKey(db_column='coc_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.conceptocontable')),
                ('pec_id', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.CASCADE, to='personas.personacurso')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'db_table': 'comprobante_pago',
            },
        ),
        migrations.CreateModel(
            name='PagoPersona',
            fields=[
                ('pap_id', models.AutoField(primary_key=True, serialize=False)),
                ('pap_fecha_hora', models.DateTimeField()),
                ('pap_tipo', models.IntegerField()),
                ('pap_valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('pap_observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Pago de Persona',
                'verbose_name_plural': 'Pagos de Personas',
                'db_table': 'pago_persona',
            },
        ),
        migrations.CreateModel(
            name='PagoCambioPersona',
            fields=[
                ('pcp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pcp_fecha_hora', models.DateTimeField()),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('pap_id', models.ForeignKey(db_column='pap_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.pagopersona')),
            ],
            options={
                'verbose_name': 'Cambio en Pago de Persona',
                'verbose_name_plural': 'Cambios en Pagos de Personas',
                'db_table': 'pago_cambio_persona',
            },
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('ppa_id', models.AutoField(primary_key=True, serialize=False)),
                ('ppa_valor', models.DecimalField(decimal_places=6, max_digits=21)),
                ('ppa_observacion', models.TextField(blank=True, null=True)),
                ('ppa_vigente', models.BooleanField()),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('pap_id', models.ForeignKey(blank=True, db_column='pap_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.pagopersona')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'verbose_name': 'Prepago',
                'verbose_name_plural': 'Prepagos',
                'db_table': 'prepago',
            },
        ),
        migrations.CreateModel(
            name='PagoComprobante',
            fields=[
                ('pco_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpa_id', models.ForeignKey(db_column='cpa_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.comprobantepago')),
                ('pap_id', models.ForeignKey(db_column='pap_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.pagopersona')),
            ],
            options={
                'verbose_name': 'Pago asociado a Comprobante',
                'verbose_name_plural': 'Pagos asociados a Comprobantes',
                'db_table': 'pago_comprobante',
                'unique_together': {('pap_id', 'cpa_id')},
            },
        ),
    ]
