# Generated by Django 5.2.7 on 2025-11-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0003_initial'),
        ('cursos', '0002_initial'),
        ('geografia', '0001_initial'),
        ('maestros', '0001_initial'),
        ('pagos', '0002_initial'),
        ('personas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('archivo_relacionado', models.ForeignKey(db_column='archivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_asociados', to='archivos.archivo')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Documento de Persona',
                'verbose_name_plural': 'Documentos de Personas',
                'db_table': 'preinscripcion_documento',
            },
        ),
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('en_revision_grupo', 'En Revisión (Grupo)'), ('en_revision_distrito', 'En Revisión (Distrito)'), ('en_revision_zona', 'En Revisión (Zona)'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('confirmado_pago', 'Pago Confirmado'), ('acreditado', 'Acreditado'), ('en_lista_espera', 'En Lista de Espera')], default='borrador', max_length=20)),
                ('cuota_asignada', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitado_fecha', models.DateTimeField(blank=True, null=True)),
                ('en_lista_espera', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('version_optimistic_lock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmado_por_pago', models.ForeignKey(blank=True, db_column='confirmado_por_pago_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscripciones_confirmadas', to='pagos.pagopersona')),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='cursos.curso')),
                ('grupo_asignado', models.ForeignKey(blank=True, db_column='grupo_asignado_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='geografia.grupo')),
                ('habilitado_por', models.ForeignKey(blank=True, db_column='habilitado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscripciones_validadas', to='usuarios.usuario')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='personas.persona')),
                ('rama', models.ForeignKey(blank=True, db_column='rama_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.rama')),
            ],
            options={
                'verbose_name': 'Preinscripción',
                'verbose_name_plural': 'Preinscripciones',
                'db_table': 'preinscripcion',
                'unique_together': {('persona', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='PreinscripcionEstadoLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('en_revision_grupo', 'En Revisión (Grupo)'), ('en_revision_distrito', 'En Revisión (Distrito)'), ('en_revision_zona', 'En Revisión (Zona)'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('confirmado_pago', 'Pago Confirmado'), ('acreditado', 'Acreditado'), ('en_lista_espera', 'En Lista de Espera')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('en_revision_grupo', 'En Revisión (Grupo)'), ('en_revision_distrito', 'En Revisión (Distrito)'), ('en_revision_zona', 'En Revisión (Zona)'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('confirmado_pago', 'Pago Confirmado'), ('acreditado', 'Acreditado'), ('en_lista_espera', 'En Lista de Espera')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('cambiado_por', models.ForeignKey(blank=True, db_column='cambiado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscripcion_estado_cambios', to='usuarios.usuario')),
                ('preinscripcion', models.ForeignKey(db_column='preinscripcion_id', on_delete=django.db.models.deletion.CASCADE, related_name='estado_logs', to='preinscripcion.preinscripcion')),
            ],
            options={
                'verbose_name': 'Log de Estado de Preinscripción',
                'verbose_name_plural': 'Logs de Estado de Preinscripciones',
                'db_table': 'preinscripcion_estado_log',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CupoConfiguracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cupo_total', models.IntegerField()),
                ('cupo_usado', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='cupos_config', to='cursos.curso')),
                ('rama', models.ForeignKey(blank=True, db_column='rama_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.rama')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='maestros.rol')),
            ],
            options={
                'verbose_name': 'Configuración de Cupo',
                'verbose_name_plural': 'Configuraciones de Cupos',
                'db_table': 'cupo_configuracion',
                'unique_together': {('curso', 'rol', 'rama')},
            },
        ),
    ]
