# Generated by GitHub Copilot on 2025-10-27
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="rut",
            field=models.CharField(max_length=15, db_index=True, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="persona",
            name="grupo",
            field=models.ForeignKey(
                to="catalog.gruposcout",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="personas",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="rama",
            field=models.ForeignKey(
                to="catalog.rama",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="personas",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="direccion",
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="telefono",
            field=models.CharField(max_length=15, blank=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="nombres",
            field=models.CharField(max_length=50, db_index=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_nacimiento",
            field=models.DateField(null=True, blank=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(fields=["nombres"], name="idx_persona_nombres"),
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(fields=["fecha_nacimiento"], name="idx_persona_fnac"),
        ),
    ]
