# Generated by Django 5.0.7 on 2025-10-29 18:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(db_column='apl_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='apl_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='apl_vigente', default=True)),
            ],
            options={
                'db_table': 'aplicacion',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(db_column='pel_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='pel_descripcion', max_length=50)),
                ('vigente', models.BooleanField(db_column='pel_vigente', default=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(db_column='usu_id', primary_key=True, serialize=False)),
                ('ruta_foto', models.CharField(blank=True, db_column='usu_ruta_foto', max_length=255, null=True)),
                ('vigente', models.BooleanField(db_column='usu_vigente', default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('perfil', models.ForeignKey(db_column='pel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.perfil')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAplicacion',
            fields=[
                ('id', models.AutoField(db_column='pea_id', primary_key=True, serialize=False)),
                ('ingresar', models.BooleanField(db_column='pea_ingresar')),
                ('modificar', models.BooleanField(db_column='pea_modificar')),
                ('eliminar', models.BooleanField(db_column='pea_eliminar')),
                ('consultar', models.BooleanField(db_column='pea_consultar')),
                ('aplicacion', models.ForeignKey(db_column='apl_id', on_delete=django.db.models.deletion.CASCADE, to='autenticacion.aplicacion')),
                ('perfil', models.ForeignKey(db_column='pel_id', on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfil')),
            ],
            options={
                'db_table': 'perfil_aplicacion',
            },
        ),
    ]
